### PR TITLE
Color update tooling

### PR DESCRIPTION
**Pull request by corneliusroemer**
Helps update the color strings based on the color scheme we seem to have been using (which gets also committed to the repo)

Usage:
```
python src/replace_colors.py --prev-row 22 --future-row 23
```

This replaces all strings in row 22 of the scheme with those in the same column/position of row 23. It also prints which new colors to use for the new clades.

### CODE REVIEW

**Comment by emmahodcroft** [comment]
To clarify, do you add a new cluster before or after you run the above script? I'm guessing above, and then just duplicate the 'end' colour... or?

**Comment by corneliusroemer** [comment]
>To clarify, do you add a new cluster before or after you run the above script? I'm guessing before, and then just duplicate the 'end' colour... or?

I think it doesn't matter, either works. I add the new clade first duplicating an existing color, then change later once the script has told me which color to use.

**Comment by emmahodcroft** [comment]
Can we add some step-by-step instructions on how to update the clade tree? It would be more safely redundant if any of us could (in theory anyway) do these updates.

**Comment by corneliusroemer** [comment]
1. Add new clade to `src/clades.json` structure, in the right place
2. Run `https://github.com/nextstrain/ncov-clades-schema/blob/master/src/replace_colors.py` with the right parameters (old number of clades and new number of clades). Currently `--prev-row` should (probably) be 24. If a single clade is added, `--future-row` should be 25: `python src/replace_colors.py --prev-row 24 --future-row 25`
3. Set the colors of new clades to the ones suggested by the script (written to stdout)
4. Adjust the width of the svg as necessary in: `src/components/NextstrainCladesSchema.tsx`
5. Check results using e.g. `yarn dev` (after dev setup)
6. Commit, push
7. Save produced svg and update `clades.svg` in this repo (this is where the README and potentially also Nextclade gets the svg from, so this needs to be updated for changes to take effect), see https://github.com/nextstrain/ncov-clades-schema/commit/738d42762aec411c5da6e78d32b1c235601b08a5

**Comment by corneliusroemer** [comment]
Added this to the README @emmahodcroft 
https://github.com/nextstrain/ncov-clades-schema/blob/master/README.md#updating-with-new-clades

**Comment by emmahodcroft** [comment]
Fantastic Cornelius! If you and Trevor get swept away to fame and fortune, those of us left behind can continue to update the clade schema 😉

**Pull request merged**
